server:
  port: 8084

spring:
  application:
    name: report-service
  datasource:
    url: jdbc:postgresql://database:5432/report-service
    username: postgres
    password: admin1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  main:
    allow-bean-definition-overriding: true
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.webservices.WebServicesAutoConfiguration
  security:
    basic:
      enabled: false