version: '3.8'

services:
  api-gateway:
    build:
      context: . # Contexto actual, donde se encuentra el Dockerfile
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "8080:8080" # Mapea el puerto 8080 del host al puerto 8080 del contenedor
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # Monta el archivo de configuración nginx.conf en el contenedor
    networks:
      - biblioteca-network # Red compartida con los microservicios

networks:
  biblioteca-network:
    external: true # Asegúrate de que la red ya exista o crea una global en el docker-compose principal
