server:
  port: 8989
  shutdown: graceful

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # Activa el descubrimiento automático de rutas desde Eureka
          lower-case-service-id: true  # Convierte los nombres de los servicios a minúsculas
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "http://localhost:3000"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowed-headers: "*"
            allow-credentials: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # URL del servidor Eureka
    register-with-eureka: false  # El Gateway no se registra como servicio
    fetch-registry: true  # Habilita la obtención del registro de servicios
