//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRUEBAS_LOGIN.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Books
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Books()
        {
            this.Loans = new HashSet<Loans>();
        }
        [Display(Name ="#")]
        public int id { get; set; }
        [Display(Name = "Título")]
        public string title { get; set; }
        [Display(Name = "Autor")]

        public string author { get; set; }
        [Display(Name = "Categoría")]
        public string category { get; set; }
        [Display(Name = "Total de Copias")]
        public int total_copies { get; set; }
        [Display(Name = "Copias Disponibles")]
        public int available_copies { get; set; }
        [Display(Name = "ISBN")]
        public string isbn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Loans> Loans { get; set; }
    }
}
