//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRUEBAS_LOGIN.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Loans
    {
        [Display(Name ="#")]
        public int id { get; set; }
        [Display(Name = "Id Usuario")]
        public int user_id { get; set; }
        [Display(Name = "Id Libro")]
        public int book_id { get; set; }
        [Display(Name = "Fecha de Préstamo")]
        public System.DateTime loan_date { get; set; }
        [Display(Name = "Fecha de Devolución")]
        public System.DateTime due_date { get; set; }
        [Display(Name = "Fecha de Devolución")]
        public Nullable<System.DateTime> return_date { get; set; }
        [Display(Name = "Multa")]
        public Nullable<decimal> fine { get; set; }

    
        public virtual Books Books { get; set; }
        public virtual Users Users { get; set; }
    }
}
