//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRUEBAS_LOGIN.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Notifications
    {
        [Display(Name = "#")]
        public int id { get; set; }
        [Display(Name = "Id Usuario")]

        public int user_id { get; set; }
        [Display(Name = "Mensaje")]
        public string message { get; set; }
        [Display(Name = "Enviado el")]
        [DisplayFormat(ApplyFormatInEditMode =true, DataFormatString = "{0:MM/dd/yyyy}")]
        [DataType(DataType.DateTime)]

        public System.DateTime sent_at { get; set; }
        [Display(Name = "Leído el")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/dd/yyyy}")]
        [DataType(DataType.DateTime)]

        public Nullable<System.DateTime> read_at { get; set; }

    
        public virtual Users Users { get; set; }
    }
}
