//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRUEBAS_LOGIN.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users()
        {
            this.Loans = new HashSet<Loans>();
            this.Notifications = new HashSet<Notifications>();
        }

        [Display (Name="#")]
        public int id { get; set; }
        [Display(Name = "Nombre de Usuario")]
        public string username { get; set; }
        [Display(Name = "Email")]
        public string email { get; set; }
        [Display(Name = "Rol")]
        public string role { get; set; }
        [Display(Name = "Estado")]
        public bool status { get; set; }
        //[Display(Name = "Contraseña")]
        public string password { get; set; }
        [Display(Name = "ID Institucional")]
        public string id_institucional { get; set; }


    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Loans> Loans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notifications> Notifications { get; set; }
    }
}
